CREATE TABLE IF NOT EXISTS Client (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL CHECK (LENGTH(name) >= 3 AND LENGTH(name) <= 200)
);

CREATE TABLE IF NOT EXISTS Planet (
    id VARCHAR(200) NOT NULL PRIMARY KEY CHECK (id REGEXP '^[A-Z0-9]+$'),
    name VARCHAR(500) NOT NULL CHECK (LENGTH(name) >= 1 AND LENGTH(name) <= 500)
);
CREATE TABLE Ticket (
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
    client_id INT NOT NULL,
    from_planet_id VARCHAR(200) NOT NULL,
    to_planet_id VARCHAR(200) NOT NULL,
    FOREIGN KEY (client_id) REFERENCES Client(id) ON DELETE CASCADE,
    FOREIGN KEY (from_planet_id) REFERENCES Planet(id) ON DELETE CASCADE,
    FOREIGN KEY (to_planet_id) REFERENCES Planet(id) ON DELETE CASCADE
);
